#!/usr/bin/env bash
set -euo pipefail

# switch-model.sh — flip the running paq-llamacpp-server systemd service between
# pre-defined model profiles via a systemd drop-in that overrides PAQ_LLAMACPP_SERVER_ENV_FILE.
#
# Usage:
#   sudo bash scripts/switch-model.sh qwen38-16gb
#   sudo bash scripts/switch-model.sh qwen38-32gb

resolve_script_dir() {
  local source_path="${BASH_SOURCE[0]}"

  while [[ -L "$source_path" ]]; do
    local source_dir

    source_dir="$(cd -P "$(dirname "$source_path")" && pwd)"
    source_path="$(readlink "$source_path")"

    if [[ "$source_path" != /* ]]; then
      source_path="$source_dir/$source_path"
    fi
  done

  cd -P "$(dirname "$source_path")" && pwd
}

ROOT="${ROOT:-$(cd "$(resolve_script_dir)/.." && pwd)}"
SERVICE_NAME="${SERVICE_NAME:-paq-llamacpp-server.service}"
OVERRIDE_DIR="/etc/systemd/system/${SERVICE_NAME}.d"
OVERRIDE_FILE="$OVERRIDE_DIR/50-paq-llamacpp-server-env-file.conf"

declare -A PROFILES=(
  ["qwen38-16gb"]="$ROOT/dot.env.qwen38-27b-q3kxl-100k-16gb"
  ["qwen38-32gb"]="$ROOT/dot.env.qwen38-27b-q5kxl-200k-32gb"
)

print_usage() {
  cat <<EOF
Usage: sudo $0 <qwen38-16gb|qwen38-32gb>

Switch the ${SERVICE_NAME} systemd service between model profiles.

Available profiles:
EOF
  for profile in "${!PROFILES[@]}"; do
    printf '  %-12s → %s\n' "$profile" "${PROFILES[$profile]}"
  done
  exit 0
}

MODEL="${1:-}"

if [[ "$MODEL" == "-h" || "$MODEL" == "--help" || -z "$MODEL" ]]; then
  print_usage
fi

TARGET_PROFILE="${PROFILES[$MODEL]:-}"

if [[ -z "$TARGET_PROFILE" ]]; then
  echo "Error: unknown model '$MODEL'." >&2
  echo "Valid models: ${!PROFILES[*]}" >&2
  exit 1
fi

if [[ ! -f "$TARGET_PROFILE" ]]; then
  echo "Error: profile file not found: $TARGET_PROFILE" >&2
  exit 1
fi

if (( EUID != 0 )); then
  echo "Error: this script must run as root (sudo)." >&2
  exit 1
fi

echo "Switching paq-llamacpp-server to profile: $MODEL → $TARGET_PROFILE"

SERVICE_WAS_ACTIVE=0
if systemctl is-active --quiet "$SERVICE_NAME"; then
  SERVICE_WAS_ACTIVE=1
  echo "Stopping active service $SERVICE_NAME..."
  systemctl stop "$SERVICE_NAME"
fi

mkdir -p "$OVERRIDE_DIR"

cat > "$OVERRIDE_FILE" <<EOF
# Generated by switch-model.sh — do not edit manually.
# Overrides the PAQ_LLAMACPP_SERVER_ENV_FILE to select the active model profile.
[Service]
Environment=PAQ_LLAMACPP_SERVER_ENV_FILE=$TARGET_PROFILE
EOF

echo "Wrote drop-in: $OVERRIDE_FILE"

systemctl daemon-reload

if (( SERVICE_WAS_ACTIVE )); then
  echo "Starting service with new profile..."
  systemctl start "$SERVICE_NAME"

  echo
  echo "Service status:"
  systemctl --no-pager --full status "$SERVICE_NAME" || true
else
  echo
  echo "Service was not running. Start it with:"
  echo "  sudo systemctl start $SERVICE_NAME"
fi

echo
echo "Current profile: $MODEL"
echo "To switch back:  sudo bash $0 qwen38-32gb"
